#ifndef TB_WORDS_H
#define TB_WORDS_H

#ifdef TB_WORDS_IMPLEMENTATION
// Words for work list were selected to be short and common

// The rules used to select the words were
// * At least 3 letters
// * No more than 5 letters
// * The first 3 letters must be unique
// * Higher frequency words win tie-breaks
// * The word must have a frequency score of at least 2000
// * Randomly select 1024 of the valid words

// See here for the word list used
// https://users.cs.duke.edu/~ola/ap/linuxwords

// See here for the frequency list used
// https://raw.githubusercontent.com/hermitdave/FrequencyWords/refs/heads/master/content/2018/en/en_full.txt

  char *tb_words[] = {"able", "about", "abuse", "ace", "ache", "acid", "act", "acute",
                      "adapt", "add", "admit", "adore", "adult", "after", "again", "age",
                      "ago", "agree", "ahead", "aid", "aim", "air", "aisle", "alarm",
                      "album", "alert", "alive", "all", "alma", "alone", "alpha", "also",
                      "altar", "amber", "amen", "amigo", "ammo", "among", "and", "angry",
                      "ankle", "annoy", "ants", "any", "apart", "ape", "apple", "apron",
                      "arch", "are", "argue", "arise", "ark", "army", "arrow", "arson",
                      "art", "ash", "aside", "ask", "ass", "ate", "atom", "audio",
                      "aunt", "auto", "avoid", "away", "awful", "aye", "baby", "back",
                      "bad", "bag", "bail", "baker", "ball", "bank", "bar", "base",
                      "bath", "bay", "beat", "beck", "bed", "been", "begin", "being",
                      "bell", "bend", "berry", "best", "bet", "bid", "big", "bike",
                      "bill", "bingo", "bird", "bit", "black", "bless", "blind", "blood",
                      "blue", "boat", "bob", "bogus", "boil", "bold", "bomb", "bones",
                      "book", "born", "boss", "both", "bound", "bow", "boy", "brain",
                      "break", "bring", "broke", "brush", "bucks", "buddy", "buff", "bug",
                      "build", "bull", "bum", "bunch", "burn", "busy", "but", "buy",
                      "buzz", "bye", "cab", "cafe", "cage", "cake", "call", "came",
                      "can", "cap", "care", "case", "catch", "cause", "cave", "cease",
                      "cell", "cents", "chair", "check", "child", "chose", "chuck", "cigar",
                      "city", "civil", "class", "clear", "climb", "close", "club", "coach",
                      "cobra", "cock", "code", "coin", "coke", "cold", "come", "con",
                      "cool", "core", "cost", "could", "cover", "cow", "cozy", "crazy",
                      "cross", "cruel", "cry", "cubs", "cue", "cuff", "cult", "cup",
                      "cure", "cut", "cycle", "dad", "daily", "damn", "dance", "dark",
                      "dash", "date", "dawn", "day", "dead", "debt", "deck", "deep",
                      "defy", "delay", "demon", "deny", "depth", "derby", "desk", "devil",
                      "diary", "dice", "did", "die", "dig", "dime", "ding", "dip",
                      "dirty", "dish", "ditch", "dive", "dizzy", "dock", "dodge", "does",
                      "dog", "doing", "doll", "dome", "don", "door", "dope", "dose",
                      "dot", "doubt", "dove", "down", "dozen", "draw", "dream", "drink",
                      "drunk", "dry", "duck", "due", "dug", "duke", "dumb", "dust",
                      "duty", "dwarf", "dwell", "dye", "dying", "each", "eagle", "earth",
                      "easy", "eat", "echo", "eddy", "edge", "eggs", "ego", "eight",
                      "elbow", "elder", "elite", "else", "empty", "end", "enemy", "enjoy",
                      "enter", "envy", "epic", "equal", "era", "ere", "error", "essay",
                      "even", "evil", "exact", "exist", "extra", "eyes", "face", "fade",
                      "fair", "fake", "fall", "fame", "fan", "far", "fast", "fault",
                      "favor", "fear", "fed", "feel", "felt", "fence", "ferry", "fetch",
                      "fever", "few", "field", "fifth", "fight", "film", "find", "first",
                      "fish", "fit", "five", "fix", "flat", "flesh", "flies", "floor",
                      "flu", "fly", "foam", "focus", "foe", "fog", "folks", "fond",
                      "food", "for", "found", "fox", "frank", "free", "fried", "from",
                      "fruit", "fry", "fuel", "full", "fun", "fur", "fuss", "fuzzy",
                      "gag", "gain", "gale", "game", "gang", "gap", "gasps", "gate",
                      "gave", "gaze", "gear", "gel", "gem", "gene", "germs", "get",
                      "ghost", "giant", "gig", "girl", "give", "glad", "glen", "glory",
                      "glue", "goal", "god", "goes", "gold", "gone", "good", "gosh",
                      "got", "gown", "grab", "grief", "group", "grunt", "guard", "guide",
                      "gulf", "gum", "gun", "guru", "guts", "guys", "habit", "hack",
                      "had", "half", "ham", "hand", "happy", "hard", "has", "hate",
                      "haul", "have", "hawk", "hay", "hazel", "hear", "heels", "heir",
                      "help", "here", "hey", "hide", "high", "hike", "hill", "him",
                      "hint", "hip", "hired", "his", "hit", "hobby", "hog", "hold",
                      "home", "honey", "hook", "hope", "horse", "host", "hot", "house",
                      "how", "huge", "huh", "hull", "human", "hunt", "hurt", "hush",
                      "hut", "ice", "idiot", "idle", "idol", "ill", "image", "inch",
                      "inner", "input", "into", "iron", "issue", "itch", "item", "its",
                      "ivy", "jab", "jade", "jail", "jam", "jar", "jaw", "jay",
                      "jazz", "jelly", "jet", "jewel", "job", "jog", "join", "joke",
                      "jolly", "joy", "judge", "jump", "junk", "jury", "just", "keep",
                      "ken", "kept", "key", "kick", "kids", "kill", "kind", "kiss",
                      "kitty", "knew", "knife", "know", "lab", "lack", "lady", "lake",
                      "lamb", "land", "lap", "large", "last", "later", "laugh", "lava",
                      "law", "lay", "lazy", "leave", "led", "left", "legs", "lemon",
                      "lend", "less", "let", "level", "lick", "lid", "life", "light",
                      "like", "lily", "limit", "line", "lion", "list", "lit", "live",
                      "load", "lobby", "lock", "lodge", "loft", "long", "look", "lost",
                      "lot", "loud", "love", "low", "loyal", "luck", "lump", "lunch",
                      "lure", "lust", "lying", "lynch", "made", "magic", "main", "major",
                      "make", "male", "man", "map", "marry", "mass", "match", "maybe",
                      "maze", "mean", "media", "meet", "melt", "memo", "men", "mercy",
                      "mess", "met", "mice", "midst", "might", "milk", "mind", "miss",
                      "mixed", "moan", "mob", "mock", "model", "mole", "money", "mood",
                      "mop", "more", "most", "mouth", "move", "much", "mud", "mug",
                      "mule", "must", "myth", "nail", "name", "nap", "nay", "near",
                      "neck", "need", "nerve", "net", "never", "new", "next", "nice",
                      "niece", "night", "nine", "noble", "nod", "noise", "none", "noon",
                      "north", "nose", "not", "novel", "now", "numb", "nun", "nurse",
                      "nuts", "oak", "oath", "obey", "occur", "ocean", "odd", "off",
                      "often", "oil", "okay", "old", "olive", "once", "one", "onion",
                      "only", "onto", "open", "opium", "orbit", "order", "organ", "other",
                      "ought", "ounce", "our", "out", "over", "owe", "owl", "own",
                      "pack", "pad", "page", "pain", "pal", "pants", "paper", "part",
                      "past", "path", "pause", "pawn", "pay", "peace", "peck", "peel",
                      "peg", "penny", "pet", "phase", "phone", "piano", "pick", "piece",
                      "pig", "pike", "pills", "pink", "pipe", "pity", "pizza", "place",
                      "plot", "plus", "pod", "poem", "point", "poker", "pole", "pond",
                      "poor", "pop", "port", "post", "pot", "pour", "power", "pray",
                      "press", "price", "proud", "pry", "pub", "puff", "pull", "pump",
                      "punch", "puppy", "pure", "push", "put", "queen", "quite", "quote",
                      "race", "radio", "raft", "rage", "raise", "rally", "ram", "ran",
                      "rare", "rash", "rat", "raven", "raw", "ray", "razor", "real",
                      "rebel", "red", "reed", "refer", "reign", "relax", "rent", "reply",
                      "rest", "rhyme", "ribs", "rich", "ride", "rifle", "right", "ring",
                      "riot", "rip", "risk", "river", "road", "rob", "rock", "rod",
                      "rogue", "roll", "room", "rope", "roses", "rot", "round", "rover",
                      "row", "royal", "rub", "rude", "rue", "rug", "ruin", "rules",
                      "run", "rush", "sack", "sad", "safe", "sage", "sale", "same",
                      "sand", "sat", "sauce", "save", "saw", "say", "scare", "scene",
                      "score", "screw", "see", "seize", "sell", "send", "serve", "set",
                      "seven", "sew", "shall", "she", "shit", "show", "shut", "shy",
                      "sick", "side", "siege", "sighs", "silly", "since", "sip", "sir",
                      "sit", "six", "size", "skate", "skin", "skull", "sky", "slave",
                      "sleep", "slip", "slow", "slug", "sly", "small", "smelt", "smile",
                      "smoke", "snake", "sneak", "sniff", "snow", "soap", "sober", "socks",
                      "soda", "soft", "soil", "sold", "some", "son", "soon", "sorry",
                      "sound", "speak", "spit", "spot", "spray", "spy", "squad", "stay",
                      "step", "still", "stop", "strip", "stuff", "style", "sub", "such",
                      "sugar", "suit", "sum", "sun", "super", "sure", "swamp", "sweet",
                      "swim", "sword", "syrup", "table", "tag", "take", "talk", "tame",
                      "tank", "tape", "taste", "taxi", "team", "teeth", "tell", "tempt",
                      "ten", "term", "test", "text", "that", "the", "this", "those",
                      "three", "thus", "tick", "tide", "tie", "tight", "till", "time",
                      "tiny", "tired", "title", "toast", "today", "toe", "token", "told",
                      "tomb", "tone", "top", "torn", "toss", "total", "touch", "town",
                      "toy", "train", "tree", "tried", "troop", "true", "tube", "tuck",
                      "tune", "turn", "tutor", "twice", "two", "tying", "type", "uncle",
                      "under", "until", "upon", "upper", "urban", "urge", "used", "using",
                      "utter", "vague", "value", "van", "vast", "vault", "veins", "very",
                      "vest", "video", "view", "villa", "visit", "vital", "vocal", "voice",
                      "vote", "vouch", "vow", "wade", "wagon", "wait", "wake", "walk",
                      "want", "was", "watch", "wave", "wax", "way", "wear", "web",
                      "week", "weird", "well", "went", "were", "west", "wet", "what",
                      "when", "which", "who", "why", "wide", "wife", "wig", "will",
                      "wipe", "wire", "wish", "with", "woke", "wolf", "woman", "won",
                      "wood", "work", "would", "wrap", "wreck", "wrong", "yard", "year",
                      "yell", "yes", "yet", "yield", "you", "zero", "zone", "zoo"};
#else
  extern char *tb_words[];
#endif

#endif
